- src/main/java/com/example/backend/common/config/WebConfig.java
- src/main/java/com/example/backend/common/jwt/JwtTokenFilter.java
- src/main/java/com/example/backend/common/security/SecurityConfig.java
- src/main/java/com/example/backend/member/controller/MemberController.java
- src/main/java/com/example/backend/member/converter/MemberConverter.java
- src/main/java/com/example/backend/member/entity/Member.java
- src/main/java/com/example/backend/memberInfo/controller/MemberInfoController.java
- src/main/java/com/example/backend/memberInfo/converter/MemberInfoConverter.java
- src/main/java/com/example/backend/memberInfo/entity/MemberInfo.java
- src/main/java/com/example/backend/memberInfo/entity/MemberInfoImage.java
- src/main/java/com/example/backend/memberInfo/entity/dto/request/EditMemberInfoRequestDTO.java
- src/main/java/com/example/backend/memberInfo/entity/dto/response/MemberInfoDetailResponseDTO.java
- src/main/java/com/example/backend/memberInfo/repository/MemberInfoImageRepository.java
- src/main/java/com/example/backend/memberInfo/repository/MemberInfoRepository.java
- src/main/java/com/example/backend/memberInfo/service/MemberInfoService.java
- src/main/java/com/example/backend/storage/service/StorageService.java
#11
- MemberInfo Entity, Repository, Service, Controller 작성
- MemberInfoImage Entity, Repository 작성
- MemberInfo Converter 작성
1. 최초 회원가입 후 내 정보 조회
2. 내 정보 변경 후 조회
3. 이미지 변경 후 조회
4. 다른 계정으로 닉네임 중복 태그 생성 확인
> [FEATURE] 내 정보 조회 및 수정

- src/main/java/com/example/backend/lecture/controller/LectureController.java
- src/main/java/com/example/backend/lecture/converter/LectureConverter.java
- src/main/java/com/example/backend/lecture/entity/dto/request/JoinLectureRequestDTO.java
- src/main/java/com/example/backend/lecture/entity/dto/response/LectureListResponseDTO.java
- src/main/java/com/example/backend/lecture/service/LectureService.java
- src/main/java/com/example/backend/participant/converter/ParticipantConverter.java
- src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
#23
- Lecture Repository, Service, Controller 작성
- Participant Repository 작성 
1. 강의 2개 생성 ( 최대인원 1명이랑 10명 )
2. 다른 계정으로 1명 강의 참가 요청
3. 다른 계정으로 10명 강의 참가 요청 후 다시 참가 요청
4. 강의 전체 조회
5. 개최자 계정으로 내 강의 조회
6. 참가자 계정으로 내 강의 조회
7. DB
> [FEATURE] 강의 참가 및 강의 전체 조회, 내 강의 조회 개발

- src/main/java/com/example/backend/memberInfo/repository/MemberInfoRepository.java
- src/main/java/com/example/backend/review/controller/ReviewController.java
- src/main/java/com/example/backend/review/converter/ReviewConverter.java
- src/main/java/com/example/backend/review/entity/Review.java
- src/main/java/com/example/backend/review/entity/ReviewDisLike.java
- src/main/java/com/example/backend/review/entity/ReviewLike.java
- src/main/java/com/example/backend/review/entity/dto/response/ReviewAllDTO.java
- src/main/java/com/example/backend/review/entity/dto/response/ReviewDetailsDTO.java
- src/main/java/com/example/backend/review/repository/ReviewDisLikeRepository.java
- src/main/java/com/example/backend/review/repository/ReviewLikeRepository.java
- src/main/java/com/example/backend/review/service/ReviewService.java
- src/main/resources/data.sql
#25 
- like/dislike lecture -> review 수정
- like/dislike 취소 기능 추가
- review entity 에 likeCount,dislikeCount 속성 추가해 사용
like/dislike 누르고 취소 할 때 마다 카운트 증가 감소
- 리뷰 상세보기/리뷰 전체보기 : memberInfo 에서 필요한 정보 가져와 response 로 넘겨주게 수정
###사진
> Feature/#25 review member info반영

- src/main/java/com/example/backend/common/config/SwaggerConfig.java
#28 
- 스웨거에서 auth 버튼을 통해 로그인가능
- access token 을 넣으면 됨
- 현재 localHost 환경에서만 가능
> [feat] : Swagger-UI 에 Auth 버튼 추가

- src/main/java/com/example/backend/member/controller/MemberController.java
- src/main/java/com/example/backend/member/converter/MemberConverter.java
- src/main/java/com/example/backend/member/entity/dto/request/ChangePwRequestDTO.java
- src/main/java/com/example/backend/member/service/MemberService.java
- src/main/java/com/example/backend/memberInfo/converter/MemberInfoConverter.java
- src/main/java/com/example/backend/memberInfo/entity/dto/response/MemberInfoDetailResponseDTO.java
#13 
- Member Controller, Service 수정
- Member Converter 수정
- DTO 작성
1. 회원가입 후 로그인 시도
2. 비밀번호 변경 후 기존 비밀번호로 로그인 시도
3. 바꾼 비밀번호로 시도
> [FEATURE] 비밀번호 변경 개발

- src/main/java/com/example/backend/category/Category.java
- src/main/java/com/example/backend/lecture/controller/LectureController.java
- src/main/java/com/example/backend/lecture/converter/LectureConverter.java
- src/main/java/com/example/backend/lecture/entity/Lecture.java
- src/main/java/com/example/backend/lecture/entity/dto/request/CreateLectureRequestDTO.java
- src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
- src/main/java/com/example/backend/lecture/repository/LectureRepository.java
- src/main/java/com/example/backend/lecture/service/LectureService.java
- src/main/java/com/example/backend/tag/Tag.java
#44
- Category Enum 작성
- Lecture Entity 수정
- Lecture Converter 수정
- Lecture Service 수정
- Lecture Controller 수정
1. 카테고리를 포함하여 데이터 전송
2. 카테고리별 검색 시도
3. 잘못된 카테고리 검색 시도
> [FEATURE] 카테고리 생성 및 카테고리 검색 개발

- src/main/java/com/example/backend/chat/controller/ChatController.java
- src/main/java/com/example/backend/chat/converter/ChatConverter.java
- src/main/java/com/example/backend/chat/entity/ChatMessage.java
- src/main/java/com/example/backend/chat/entity/ChatRoom.java
- src/main/java/com/example/backend/chat/entity/ChatRoomMember.java
- src/main/java/com/example/backend/chat/entity/dto/MessageInfoDTO.java
- src/main/java/com/example/backend/chat/entity/dto/request/CreateChatRoomRequestDTO.java
- src/main/java/com/example/backend/chat/entity/dto/response/ChatRoomInfoResponseDTO.java
- src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
- src/main/java/com/example/backend/chat/repository/ChatRoomRepository.java
- src/main/java/com/example/backend/chat/service/ChatService.java
- src/main/java/com/example/backend/common/enums/MessageType.java
- src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
#38 
* ChatController 추가 
* entity 에 해당하는 repository 추가 
* ChatService 추가 
* DTO 추가 
* converter 추가 
* create 기능 
1.  request 형식
2. response 형식(추가예정)
> Feature/#38 채팅방 생성하기기능

- src/main/java/com/example/backend/chat/controller/ChatController.java
- src/main/java/com/example/backend/chat/converter/ChatConverter.java
- src/main/java/com/example/backend/chat/entity/dto/ChatRoomInfoDTO.java
- src/main/java/com/example/backend/chat/entity/dto/response/ChatRoomAllResponseDTO.java
- src/main/java/com/example/backend/chat/repository/ChatMessageRepository.java
- src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
- src/main/java/com/example/backend/chat/service/ChatService.java
#51 
* 유저별 채팅방 전체 조회 기능 개발
* DTO 추가 
* controller 에 API 추가 
* service에 로직 추가 
1. request/ response
> Feature/#51 유저별 채팅방 전체조회

- src/main/java/com/example/backend/chat/controller/ChatController.java
- src/main/java/com/example/backend/chat/converter/ChatConverter.java
- src/main/java/com/example/backend/chat/entity/dto/ChatRoomInfoDTO.java
- src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
- src/main/java/com/example/backend/chat/service/ChatService.java
#53 
* 채팅방 상세보기 기능 개발
* Controller API 추가
* Converter 수정
* Service 에 로직 추가 
* DTO 에 검색 기능 추가 
1. response/ request
> Feature/#53 채팅방 상세보기

- src/main/java/com/example/backend/lecture/controller/LectureController.java
- src/main/java/com/example/backend/lecture/converter/LectureConverter.java
- src/main/java/com/example/backend/lecture/entity/dto/response/LectureMapResponseDTO.java
- src/main/java/com/example/backend/lecture/service/LectureService.java
- src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
#55
- Lecture Converter, Service, Controller 작성
- LectureMapResponseDTO 작성
1. 지도 api 조회
> [Feature] 지도 api 작성

- src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
> [hotfix] : 채팅방 생성시 오류 발생 수정

- src/main/java/com/example/backend/chat/converter/ChatConverter.java
- src/main/java/com/example/backend/chat/service/ChatService.java
> [fix] : 채팅방 전체보기에서 내 프로필 사진/채팅방 상대 프로필사진 같은 이미지로 보이는 오류 수정

- src/main/java/com/example/backend/lecture/converter/LectureConverter.java
- src/main/java/com/example/backend/lecture/entity/dto/response/LectureBannerResponseDTO.java
#61
- LectureBannerResponseDTO 수정
- LectureConverter 수정
1. 변경된 응답
> [FEATURE] Banner Response DTO 수정

- src/main/java/com/example/backend/review/controller/ReviewController.java
#66 
* reqeustParam 에 "id" 와 같은 값들 추가
> [fix] : ReviewController reqeustParam 수정

- src/main/java/com/example/backend/chat/converter/ChatConverter.java
- src/main/java/com/example/backend/chat/entity/ChatMessage.java
- src/main/java/com/example/backend/chat/service/ChatService.java
#63 
* ChatMessage Service 채팅 읽음 기능 추가
> FEAT/#63 chat message 읽음기능추가

- src/main/java/com/example/backend/lecture/controller/LectureController.java
- src/main/java/com/example/backend/lecture/converter/LectureConverter.java
- src/main/java/com/example/backend/lecture/entity/dto/response/LectureDetailResponseDTO.java
- src/main/java/com/example/backend/lecture/service/LectureService.java
- src/main/java/com/example/backend/participant/converter/ParticipantConverter.java
- src/main/java/com/example/backend/participant/entity/Participant.java
- src/main/java/com/example/backend/participant/repository/ParticipantRepository.java
#67
- Participant Entity, Repository 수정
- Lecture Service, Controller 수정
- Detail DTO 수정
1. 강의 정원 10명인 강의에 11명으로 신청
2. 8명만 신청하고 남은 인원 확인
> [FEATURE] Lecture Join 예외처리

- src/main/java/com/example/backend/chat/service/ChatService.java
#65 
- 클래스 생성 멤버와 현재 유저가 같으면 채팅방 생성 불가
> FEATURE/ #65 ChatService 검증 로직 추가

- src/main/java/com/example/backend/lecture/converter/LectureConverter.java
> [Fix] 강의 상세 별점 수정

- src/main/java/com/example/backend/chat/controller/ChatController.java
- src/main/java/com/example/backend/chat/repository/ChatMessageRepository.java
- src/main/java/com/example/backend/chat/repository/ChatRoomMemberRepository.java
- src/main/java/com/example/backend/chat/service/ChatService.java
#70 
* 채팅방 삭제 기능 추가 
* Controller API 추가 
* Service 에 삭제 기능 추가 
* repository 에 검색 기능 추가 
* 자세한 내용은 커밋 참조 
1.
> Feature/#70 채팅방삭제

- src/main/java/com/example/backend/review/converter/ReviewConverter.java
- src/main/java/com/example/backend/review/entity/dto/response/ReviewAllDTO.java
- src/main/java/com/example/backend/review/entity/dto/response/ReviewDetailsDTO.java
- src/main/java/com/example/backend/review/service/ReviewService.java
#72 
* localdatetime -> localdate 로 수정
> Fix/#72 review localdate로 수정

- src/main/java/com/example/backend/review/controller/ReviewController.java
- src/main/java/com/example/backend/review/service/ReviewService.java
* 좋아요 누르기, 취소 한 API 로 모두 가능하게 수정
* 좋아요 취소 API : api/review/delete 삭제
> [fix] : like/dislike API 수정

- src/main/java/com/example/backend/review/controller/ReviewController.java
- src/main/java/com/example/backend/review/service/ReviewService.java
#75 
* 리뷰 생성시 이미지 null 인경우 400 에러 나는 부분 수정
> [fix] : 리뷰 이미지 null 일때 400 에러 수정

- src/main/java/com/example/backend/common/jwt/JwtTokenFilter.java
#82 
- JwtException 수정
1. 예외확인
> [FEATURE] 토큰 예외처리

- src/main/java/com/example/backend/common/jwt/JwtTokenFilter.java
> [Fix] 문제 해결

- src/main/java/com/example/backend/lecture/controller/LectureController.java
- src/main/java/com/example/backend/lecture/service/LectureService.java
#35
- Lecture Service, Controller 작성
1. 내가 개최한 강의 조회
2. 삭제 후 확인
3. 다른 강좌 개설 후 다른 계정으로 삭제 시도
> [FEATURE] 강의 삭제 구현

- src/main/java/com/example/backend/lecture/repository/LectureImageRepository.java
- src/main/java/com/example/backend/lecture/service/LectureService.java
> [REFACTOR] 이미지 수정 메소드 로직 수정

- src/main/java/com/example/backend/lecture/entity/Lecture.java
> [FEATURE] Cascade 설정
